/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pruebas.Categoria;
import pruebas.Herramienta;

/**
 *
 * @author Mauricio
 */
public class Ventana extends javax.swing.JFrame {
    private ArrayList<Categoria> catalogoCategoria;
    private ArrayList<Herramienta> catalogoHerramienta;
    private int contadorCategorias;
    private int contadorHerramientas;
    private DefaultComboBoxModel modeloComboBoxCatalogo;
    private Image iconoPrincipal;
    private DefaultTableModel modeloTablaCategorias;
    private DefaultTableModel modeloTablaHerramientas;
    private int contadorFilasTablaCategoria;
    private int contadorFilasTablaHerramienta;
    
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        
        //Info de la Ventana
        String nombreDelSistema = "Inventario de Herramientas";
        this.setTitle(nombreDelSistema);
        iconoPrincipal = new ImageIcon(getClass().getResource("iconoPrincipal.png")).getImage();
        this.setIconImage(iconoPrincipal);
        imagenDeInicio.setText("");
        imagenDeInicio.setIcon(new ImageIcon (getClass().getResource("iconoPrincipal1.png")));
        
        
        //Iniciar componentes de Catálogo como invisibles
        setAllComponentsInvisible();
        imagenDeInicio.setVisible(true);
        
        //Mnemonicos
        btnGuardarCategoria.setMnemonic(KeyEvent.VK_G);
        btnGuardarHerramienta.setMnemonic(KeyEvent.VK_G);
        
        //Iniciar componentes utilizados para el catalogo
        contadorCategorias = 0;
        contadorHerramientas = 0;
        catalogoCategoria = new ArrayList<Categoria>();        
        catalogoHerramienta = new ArrayList<Herramienta>();
        modeloComboBoxCatalogo = new DefaultComboBoxModel();
        comboBoxCatalogo.setModel(modeloComboBoxCatalogo);
      
        //Tabla de Catalogo
        contadorFilasTablaCategoria = contadorFilasTablaHerramienta = 0;
        modeloTablaCategorias = new DefaultTableModel();
        modeloTablaCategorias.addColumn("ID");
        modeloTablaCategorias.addColumn("Categoría");
        
        modeloTablaHerramientas = new DefaultTableModel();
        modeloTablaHerramientas.addColumn("ID");
        modeloTablaHerramientas.addColumn("Categoría");
        modeloTablaHerramientas.addColumn("Herramienta");
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnNuevaCategoria = new javax.swing.JButton();
        btnNuevaHerramienta = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        btnHerramientas = new javax.swing.JButton();
        panelCatalogo = new javax.swing.JPanel();
        etiquetaCatalogo1 = new javax.swing.JLabel();
        campoCatalogo1 = new javax.swing.JTextField();
        btnGuardarHerramienta = new javax.swing.JButton();
        etiquetaCatalogo2 = new javax.swing.JLabel();
        campoCatalogo2 = new javax.swing.JTextField();
        comboBoxCatalogo = new javax.swing.JComboBox<>();
        btnGuardarCategoria = new javax.swing.JButton();
        imagenDeInicio = new javax.swing.JLabel();
        ScrollPaneTablaCatalogo = new javax.swing.JScrollPane();
        tablaCatalogo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNuevaCategoria.setText("Nueva Categoría");
        btnNuevaCategoria.setFocusable(false);
        btnNuevaCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevaCategoria.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCategoriaActionPerformed(evt);
            }
        });

        btnNuevaHerramienta.setText("Nueva Herramienta");
        btnNuevaHerramienta.setFocusable(false);
        btnNuevaHerramienta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevaHerramienta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNuevaHerramienta.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                btnNuevaHerramientaComponentAdded(evt);
            }
        });
        btnNuevaHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaHerramientaActionPerformed(evt);
            }
        });

        btnCategorias.setText("Categorías");
        btnCategorias.setFocusable(false);
        btnCategorias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCategorias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });

        btnHerramientas.setText("Herramientas");
        btnHerramientas.setFocusable(false);
        btnHerramientas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHerramientas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHerramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHerramientasActionPerformed(evt);
            }
        });

        etiquetaCatalogo1.setText("Ingrese el nombre de la categoría");

        campoCatalogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCatalogo1ActionPerformed(evt);
            }
        });

        btnGuardarHerramienta.setText("Guardar");
        btnGuardarHerramienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarHerramientaActionPerformed(evt);
            }
        });

        etiquetaCatalogo2.setText("jLabel1");

        campoCatalogo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCatalogo2ActionPerformed(evt);
            }
        });

        comboBoxCatalogo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGuardarCategoria.setText("Guardar");
        btnGuardarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCategoriaActionPerformed(evt);
            }
        });

        imagenDeInicio.setText("jLabel1");

        tablaCatalogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ScrollPaneTablaCatalogo.setViewportView(tablaCatalogo);

        javax.swing.GroupLayout panelCatalogoLayout = new javax.swing.GroupLayout(panelCatalogo);
        panelCatalogo.setLayout(panelCatalogoLayout);
        panelCatalogoLayout.setHorizontalGroup(
            panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCatalogoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiquetaCatalogo2)
                            .addComponent(campoCatalogo2)
                            .addComponent(etiquetaCatalogo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(imagenDeInicio))
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addComponent(comboBoxCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCatalogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btnGuardarCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardarHerramienta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneTablaCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCatalogoLayout.setVerticalGroup(
            panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCatalogoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPaneTablaCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCatalogoLayout.createSequentialGroup()
                        .addComponent(etiquetaCatalogo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCatalogo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addComponent(etiquetaCatalogo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoCatalogo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imagenDeInicio))
                        .addGap(45, 45, 45)
                        .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGuardarHerramienta)
                            .addComponent(btnGuardarCategoria))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNuevaHerramienta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevaCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevaCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevaHerramienta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCategorias)
                        .addGap(15, 15, 15)
                        .addComponent(btnHerramientas)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabPane.addTab("Catálogo", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        tabPane.addTab("Inventario", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 479, Short.MAX_VALUE)
        );

        tabPane.addTab("Informes", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHerramientasActionPerformed
        setAllComponentsInvisible();
        tablaCatalogo.setVisible(true);
        ScrollPaneTablaCatalogo.setVisible(true);
        tablaCatalogo.setModel(modeloTablaHerramientas);
    }//GEN-LAST:event_btnHerramientasActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
        setAllComponentsInvisible();
        tablaCatalogo.setVisible(true);
        ScrollPaneTablaCatalogo.setVisible(true);
        
        tablaCatalogo.setModel(modeloTablaCategorias);
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnNuevaHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaHerramientaActionPerformed
        setAllComponentsInvisible();
        etiquetaCatalogo1.setVisible(true);
        etiquetaCatalogo1.setText("Seleccione la categoría de la herramienta");
        etiquetaCatalogo2.setVisible(true);
        etiquetaCatalogo2.setText("Ingrese el nombre de la herramienta");
        campoCatalogo1.setVisible(false);
        campoCatalogo2.setVisible(true);
        campoCatalogo2.setText("");
        btnGuardarHerramienta.setVisible(true);
        comboBoxCatalogo.setVisible(true);
        
        
    }//GEN-LAST:event_btnNuevaHerramientaActionPerformed

    private void btnNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCategoriaActionPerformed
        setAllComponentsInvisible();
        etiquetaCatalogo1.setText("Ingrese el nombre de la categoría");
        etiquetaCatalogo1.setVisible(true);
        campoCatalogo1.setVisible(true);
        campoCatalogo1.setText("");
        btnGuardarCategoria.setVisible(true);
       
                
    }//GEN-LAST:event_btnNuevaCategoriaActionPerformed

    private void btnNuevaHerramientaComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_btnNuevaHerramientaComponentAdded
       //No se usa              
    }//GEN-LAST:event_btnNuevaHerramientaComponentAdded

    private void btnGuardarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCategoriaActionPerformed
        if (!campoCatalogo1.getText().equals("")){
            catalogoCategoria.add(new Categoria(campoCatalogo1.getText().toUpperCase(), ++contadorCategorias));
            
            //Se guarda el objeto Categoría temporalmente
            Categoria c = catalogoCategoria.get(contadorCategorias -1);
            //Se agrega la Categoría al modelo del comboBox
            modeloComboBoxCatalogo.addElement(c);
            
            //Se agrega la Categoría al modelo de la tabla Categorias
            String [] datos = {String.valueOf(c.getIdCategoria()), c.getNombreCategoria()};
            modeloTablaCategorias.addRow(datos);
            
            
            campoCatalogo1.setText("");
            JOptionPane.showMessageDialog(
                rootPane, "Categoría guardada exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }else
        JOptionPane.showMessageDialog(
            rootPane, "Ingrese el nombre de la categoria", "Advertencia", JOptionPane.WARNING_MESSAGE);

    }//GEN-LAST:event_btnGuardarCategoriaActionPerformed

    private void campoCatalogo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCatalogo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCatalogo2ActionPerformed

    private void btnGuardarHerramientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarHerramientaActionPerformed
        if(modeloComboBoxCatalogo.getSize() < 1){
            JOptionPane.showMessageDialog(
                rootPane, "¡Ups, No hay Categorias!\nIngrese Nueva Categoria", "Advertencia", JOptionPane.WARNING_MESSAGE);
        } else
        if(!"".equals(campoCatalogo2.getText())){
            catalogoHerramienta.add(new Herramienta(
                campoCatalogo2.getText().toUpperCase(),(Categoria) comboBoxCatalogo.getSelectedItem(), ++contadorHerramientas));
            
            //Se guarda temporalmente la herramienta
            Herramienta h = catalogoHerramienta.get(contadorHerramientas-1);
            //Se guarda la Herramienta en el modelo de la Tabla Herramientas
            String[] datos = {String.valueOf(h.getIdHerramienta()), h.getCategoriaHerramienta().toString(), h.getNombreHerramienta()};
            modeloTablaHerramientas.addRow(datos);

        JOptionPane.showMessageDialog(
            rootPane, "Herramienta guardada exitosamente", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        campoCatalogo2.setText("");
        comboBoxCatalogo.setSelectedIndex(0);
        }else JOptionPane.showMessageDialog(
            rootPane, "Añada el nombre de la herramienta", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnGuardarHerramientaActionPerformed

    private void campoCatalogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCatalogo1ActionPerformed
        System.out.println("Algo pasó");
    }//GEN-LAST:event_campoCatalogo1ActionPerformed

    
    private void setAllComponentsInvisible(){
        switch(tabPane.getSelectedIndex()){
            case 0:
                //Elementos del panel 1 "Catalogo"
                etiquetaCatalogo1.setVisible(false);
                etiquetaCatalogo2.setVisible(false);
                campoCatalogo1.setVisible(false);
                campoCatalogo2.setVisible(false);
                btnGuardarCategoria.setVisible(false);
                btnGuardarHerramienta.setVisible(false);
                comboBoxCatalogo.setVisible(false);
                tablaCatalogo.setVisible(false);
                ScrollPaneTablaCatalogo.setVisible(false);
                imagenDeInicio.setVisible(false);
                System.out.println("Catalogo Activo");
                break;
            case 1:
                //Elementos del panel 2 "Inventario"
                //Por hacer
            case 2:
                //Elementos del panel 3 "Informes"
                //Por Hacer
 
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneTablaCatalogo;
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnGuardarCategoria;
    private javax.swing.JButton btnGuardarHerramienta;
    private javax.swing.JButton btnHerramientas;
    private javax.swing.JButton btnNuevaCategoria;
    private javax.swing.JButton btnNuevaHerramienta;
    private javax.swing.JTextField campoCatalogo1;
    private javax.swing.JTextField campoCatalogo2;
    private javax.swing.JComboBox<String> comboBoxCatalogo;
    private javax.swing.JLabel etiquetaCatalogo1;
    private javax.swing.JLabel etiquetaCatalogo2;
    private javax.swing.JLabel imagenDeInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelCatalogo;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tablaCatalogo;
    // End of variables declaration//GEN-END:variables
}
